import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import BarraLateral from '../../../components/admin/barra_lateral';
import NavBar from '../../../components/admin/navbar';

export default function Home() {
   //   const [Action, fetchAction] = useState([]);
   // //   const [tablaAction, setTablaUsuarios]= useState([]);
   //   const [busqueda, fetchBusqueda]= useState("");

   //   const getData = () => {
   //     fetch('http://127.0.0.1:8000/order/my_action/')
   //       .then((res) => res.json())
   //       .then((res) => {
   //         fetchAction(res)
   //         console.log(res);
   //       })
   //   }

   //   const handleChange=e=>{
   //    fetchBusqueda(e.target.value);
   //    // console.log("Búsqueda:" +e.target.value);
   //    filtrar(e.target.value);
   //  }

   //   const filtrar=(terminoBusqueda)=>{
   //    var resultadosBusqueda=Action.filter((action)=>{
   //      if(action.sale_price.toString().toLowerCase().includes(terminoBusqueda.toLowerCase())
   //      || action.quantity.toString().toLowerCase().includes(terminoBusqueda.toLowerCase())
   //      ){
   //        return action;
   //      }
   //    });
   //    fetchAction(resultadosBusqueda);
   //  }

   // useEffect(() => {
   //   getData()
   // }, [])

   return (
      <div className="">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className="bg-black">
            <body>


               <div>
                  <NavBar />
                  <div class="flex overflow-hidden bg-white pt-10">
                     <BarraLateral />
                     <div class="bg-gray-900 opacity-50 hidden fixed inset-0 z-10" id="sidebarBackdrop"></div>
                     <div id="main-content" class="h-full w-full bg-gray-50 relative overflow-y-auto lg:ml-64">
                        <main>
                           <div class="pt-10 px-5">
                              <div class="w-full gap-4">
                                 <section class="container mx-auto font-mono">
                                    <div class="w-30 mb-10 px-5 overflow-hidden rounded-lg shadow-lg">

                                       <div class="w-full overflow-x-auto">

                                          <a href="http://localhost:3000/admin/order/action" class="text-xl hidden sm:inline-flex ml-1 text-white bg-red-600 hover:bg-red-700 focus:ring-10 focus:ring-cyan-200 font-medium rounded-lg px-10 py-5 text-center items-center mr-3">
                                             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash -ml-1 mr-2 h-4 w-4" viewBox="0 0 16 16">
                                                {/* <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/> */}
                                                {/* <path fill-rule="evenodd"/> */}
                                             </svg>
                                             ACCIONES
                                          </a>

                                          <a href="http://localhost:3000/admin/order/bond" class="text-xl hidden sm:inline-flex ml-5 text-white bg-red-600 hover:bg-red-700 focus:ring-10 focus:ring-cyan-200 font-medium rounded-lg px-10 py-5 text-center items-center mr-3">

                                             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash -ml-1 mr-2 h-4 w-4" viewBox="0 0 16 16">
                                                {/* <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/> */}
                                                {/* <path fill-rule="evenodd"/> */}
                                             </svg>
                                             BONOS
                                          </a>

                                          <a href="http://localhost:3000/admin/order/investment" class="text-xl hidden sm:inline-flex ml-5 text-white bg-red-600 hover:bg-red-700 focus:ring-10 focus:ring-cyan-200 font-medium rounded-lg px-10 py-5 text-center items-center mr-3">
                                             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash -ml-1 mr-2 h-4 w-4" viewBox="0 0 16 16">
                                                {/* <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/> */}
                                                {/* <path fill-rule="evenodd"/> */}
                                             </svg>
                                             INVERSIONES
                                          </a>

                                          <a href="http://localhost:3000/admin/order/pedidos" class="text-xl hidden sm:inline-flex ml-5 text-white bg-red-600 hover:bg-red-700 focus:ring-10 focus:ring-cyan-200 font-medium rounded-lg px-10 py-5 text-center items-center mr-3">
                                             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash -ml-1 mr-2 h-4 w-4" viewBox="0 0 16 16">
                                                {/* <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/> */}
                                                {/* <path fill-rule="evenodd"/> */}
                                             </svg>
                                             PEDIDOS
                                          </a>

                                       </div>

                                    </div>
                                 </section>
                              </div>
                           </div>
                        </main>
                     </div>
                  </div>
               </div>
            </body>
         </main>
      </div>
   )
}

