import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import axios from 'axios';
import BarraLateral from '../../../components/admin/barra_lateral';
import NavBar from '../../../components/admin/navbar';
import LinksNA from '../../../components/admin/links';
import TablaUsuarios from '../../../components/tabla/tablaUsuarios';

export default function Home() {

   return (
      <div className="">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className="bg-black">
            <body>

               <div>
                  <NavBar />
                  <div class="flex overflow-hidden bg-white pt-16">
                     <BarraLateral />
                     <div class="bg-gray-900 opacity-50 hidden fixed inset-0 z-10" id="sidebarBackdrop"></div>
                     <div id="main-content" class="h-full w-full bg-gray-50 relative overflow-y-auto lg:ml-64">
                        <main>
                           <div class="pt-6 px-4">
                              <div class="w-full">
                                 <section class="container mx-auto p-6 font-mono">
                                    <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
                                       <LinksNA />
                                       <div class="w-full grid grid-cols-1">
                                          <div class="">
                                             {/*TABLE*/}
                                             <TablaUsuarios />
                                          </div>
                                       </div>
                                    </div>
                                 </section>
                              </div>
                           </div>
                        </main>
                     </div>
                  </div>
                  <script async defer src="https://buttons.github.io/buttons.js"></script>
                  <script src="https://demo.themesberg.com/windster/app.bundle.js"></script>
               </div>
            </body>
         </main>
      </div>
   )
}